

const AmlKyc = () => {
    return (
        <section className='py-[60px] bg-bgProfile relative h-full bg-no-repeat bg-contain bg-center '>
            <div className='container text-white'>
                <h2 className='text-[32px] mb-[45px]'>AML & KYC policy</h2>
                <div className=' flex flex-col h-[650px] overflow-y-scroll scrollbar-thumb-green scrollbar-track-darkGreen scrollbar-thin'>
                THE PURPOSES OF THE MyAltCoins ANTI-MONEY LAUNDERING, COUNTER-TERRORIST FINANCING AND KNOW YOUR CUSTOMER POLICY (HEREINAFTER — THE “AML/KYC POLICY“) IS TO IDENTIFY, PREVENT AND MITIGATE POSSIBLE RISKS OF CRYPTO DOWNGRADE BEING INVOLVED IN ILLEGAL ACTIVITY. <br/>
                TO CONFIRM WITH INTERNATIONAL AND LOCAL REGULATIONS, CRYPTO DOWNGRADE HAS IMPLEMENTED EFFECTIVE INTERNAL PROCEDURES TO PREVENT MONEY LAUNDERING, TERRORIST FINANCING, DRUG AND HUMAN TRAFFICKING, PROLIFERATION OF WEAPONS OF MASS DESTRUCTION, CORRUPTION AND BRIBERY AND TO REACT CORRESPONDINGLY IN CASE OF ANY FORM OF SUSPICIOUS ACTIVITY FROM ITS USERS.
                MONEY LAUNDERING CAN BE DEFINED AS: ‘THE CONVERSION OR TRANSFER OF PROPERTY, KNOWING THAT SUCH PROPERTY IS DERIVED FROM CRIMINAL ACTIVITY, OR FROM AN ACT OF PARTICIPATION IN SUCH ACTIVITY, FOR THE PURPOSES OF CONCEALING OR DISGUISING THE ILLICIT ORIGIN OF THE PROPERTY, OR ASSISTING ANY PERSON WHO IS INVOLVED IN THE COMMISSION OF SUCH ACTIVITY TO EVADE THE LEGAL CONSEQUENCES OF HIS ACTION.’ TERRORIST FINANCING CAN BE DEFINED AS: ‘THE WILFUL PROVISION OR COLLECTION, BY ANY MEANS, DIRECTLY OR INDIRECTLY, OF FUNDS WITH THE INTENTION THAT THE FUNDS SHOULD BE USED, OR IN THE KNOWLEDGE THAT THEY ARE TO BE USED, IN ORDER TO CARRY OUT TERRORIST ACTS.’ <br/>
                ALL FIRMS MUST ADHERE TO THE MONEY LAUNDERING, TERRORIST FINANCING AND TRANSFER OF FUNDS (INFORMATION ON THE PAYER) REGULATIONS 2017 (MLRS), AND BE AWARE OF THE GUIDANCE SET DOWN BY THE JOINT MONEY LAUNDERING STEERING GROUP (JMLSG) WHICH PROVIDES GUIDELINES WITHIN THE UNITED KINGDOM ON HOW FIRMS SHOULD CONDUCT DUE DILIGENCE ON THEIR CUSTOMERS, AND THE RECOMMENDATIONS FROM THE FINANCIAL ACTION TASK FORCE (FATF), AN INTER-GOVERNMENTAL BODY WHOSE PURPOSE IS THE DEVELOPMENT AND PROMOTION OF NATIONAL AND INTERNATIONAL POLICIES TO COMBAT MONEY LAUNDERING AND TERRORIST FINANCING. OTHER LEGISLATION IN RELATION TO AML/KYC ARE: <br/>
                5TH ANTI-MONEY LAUNDERING DIRECTIVE ((EU) 2018/843) <br/>
                THE PROCEEDS OF CRIME ACT 2002; <br/>
                TERRORISM ACT 2000 AND 2001; <br/>
                COUNTER-TERRORISM ACT 2008; <br/>
                HM TREASURY SANCTION NOTICES; <br/>
                FCA HANDBOOK. <br/>
                AML/KYC POLICY INCLUDES: <br/>
                <br/>
                VERIFICATION PROCEDURE; <br/>
                ROLE OF THE CHIEF COMPLIANCE OFFICER; <br/>
                TRANSACTIONS MONITORING; <br/>
                RISK ASSESSMENT: <br/>
                COUNTRY OF RESIDENCE. <br/>
                VERIFICATION PROCEDURES <br/>
                TO HELP FIGHT THE FUNDING OF TERRORISM AND MONEY LAUNDERING ACTIVITIES, THE LAW REQUIRES ALL FINANCIAL INSTITUTIONS TO OBTAIN, VERIFY AND RECORD INFORMATION THAT IDENTIFIES EACH PERSON OR ENTITY WHO OPENS AN ACCOUNT. WE ARE REQUIRED BY LAW TO ASK YOU TO PROVIDE YOUR NAME, ADDRESS, DATE OF BIRTH AND OTHER INFORMATION ABOUT YOU, YOUR ORGANISATION OR PERSONS RELATED TO YOUR ORGANISATION THAT WILL ALLOW US TO IDENTIFY YOU BEFORE WE APPROVE YOUR ACCOUNT. WE ALSO MAY ASK YOU TO PROVIDE CERTAIN IDENTIFYING DOCUMENTS, SUCH AS YOUR DRIVER’S LICENSE OR PASSPORT OR YOUR ORGANISATION’S ARTICLES OF INCORPORATION AND MAY OBTAIN CREDIT AND OTHER CONSUMER REPORTS TO ASSIST US IN VERIFYING YOUR IDENTITY AND IN DETERMINING WHETHER YOU SATISFY OUR ACCOUNT CRITERIA. UNLESS YOU PROVIDE THE REQUESTED INFORMATION AND DOCUMENTATION, WE MAY NOT BE ABLE TO OPEN YOUR ACCOUNT. <br/>
                BY APPLYING FOR AN CRYPTO DOWNGRADE ACCOUNT, YOU AGREE TO PROVIDE THE INFORMATION AND DOCUMENTATION REQUESTED BY CRYPTO DOWNGRADE AND CONSENT TO MyAltCoins ACQUISITION OF CREDIT AND OTHER CONSUMER REPORTS ABOUT YOU FOR THE PURPOSES DESCRIBED ABOVE. <br/>
                THE MyAltCoins CUSTOMER DUE DILIGENCE (“CDD“) PROCEDURE REQUIRES THE USERS TO PROVIDE CRYPTO DOWNGRADE WITH RELIABLE, INDEPENDENT SOURCE DOCUMENTS TO IDENTIFY THEM AND CONFIRM THEIR RESIDENTIAL ADDRESS. SUCH DOCUMENTS MAY INCLUDE, FOR EXAMPLE, A NATIONAL ID CARD, AN INTERNATIONAL PASSPORT, A BANK STATEMENT, A UTILITY BILL. FOR SUCH PURPOSES, CRYPTO DOWNGRADE RESERVES THE RIGHT TO COLLECT THE USERS’ IDENTIFICATION INFORMATION FOR THE PURPOSES OF COMPLIANCE WITH ITS AML/CFT AND KYC POLICY. <br/>
                CRYPTO DOWNGRADE WILL TAKE STEPS TO CONFIRM THE AUTHENTICITY OF DOCUMENTS AND INFORMATION PROVIDED BY USERS. CRYPTO DOWNGRADE WILL ALSO LOOK TO VERIFY IDENTIFICATION INFORMATION THROUGH SECONDARY SOURCES, AND CRYPTO DOWNGRADE RESERVES THE RIGHT TO INVESTIGATE FURTHER THE CASES OF USERS WHERE CRYPTO DOWNGRADE IS NOT SATISFIED WITH THE DOCUMENTATION SUBMITTED.
                CRYPTO DOWNGRADE RESERVES THE RIGHT TO VERIFY THE IDENTITY OF THE USER ON AN ONGOING BASIS, ESPECIALLY WHEN ITS IDENTIFICATION INFORMATION HAS BEEN CHANGED OR ITS ACTIVITIES APPEAR SUSPICIOUS (UNUSUAL FOR A PARTICULAR USER). IN ADDITION, CRYPTO DOWNGRADE RESERVES THE RIGHT TO REQUEST FROM THE USERS CURRENT DOCUMENTS, EVEN IF THEY HAVE BEEN AUTHENTICATED IN THE PAST.
                INFORMATION ABOUT THE USER’S IDENTIFICATION WILL BE COLLECTED, STORED, SHARED AND PROTECTED STRICTLY IN ACCORDANCE WITH THE MyAltCoins PRIVACY POLICY AND RELEVANT RULES. THE USER AGREES THAT IF ANY INFORMATION PROVIDED IN THE ACCOUNT APPLICATION CHANGES, CEASES TO BE TRUE OR BECOMES MATERIALLY MISLEADING (INCLUDING, BUT NOT LIMITED TO, THE OWNERSHIP OF THE ACCOUNT) THEN THE USER WILL NOTIFY CRYPTO DOWNGRADE OF THE CHANGES. <br/>
                AFTER CONFIRMING THE IDENTITY OF THE USER, CRYPTO DOWNGRADE MAY REFUSE TO PROVIDE SERVICES TO THE USER IF MyAltCoins SERVICES ARE SUSPECTED TO BE USED FOR THE PURPOSES OF CONDUCTING ILLEGAL <br/>
                ACTIVITIES. CRYPTO <br/>
                DOWNGRADE HAS A REGULATORY REQUIREMENT TO VERIFY THE SOURCES OF FIAT MONEY AND/OR CRYPTOCURRENCY TO KNOW THAT THE SOURCES OF THE FUNDS THAT USERS USE TO TRADE WITH ARE LEGITIMATE. CRYPTO DOWNGRADE WILL REQUIRE EVIDENCE OF THE SOURCE OF FUNDS; THIS MAY INCLUDE BANK STATEMENTS FOR FIAT MONEY OR A VIDEO SHOWING WALLET TRANSACTION DETAILS FOR CRYPTOCURRENCY.
                USERS WHO INTEND TO USE PAYMENT CARDS FOR THE PURPOSE OF CONSUMING SERVICES MUST UNDERGO A CARD CHECK IN ACCORDANCE WITH THE INSTRUCTIONS AVAILABLE ON THE MyAltCoins SITE. <br/>
                CRYPTO DOWNGRADE USES INDEPENDENT THIRD-PARTY COMPANIES FOR THE FOLLOWING: <br/>
                CHECK USERS AGAINST POLITICALLY EXPOSED PERSON’S (PEP) AND SANCTIONS LISTS AS WELL AS CHECKS FOR ADVERSE MEDIA. <br/>
                ASSESS USER’S CRYPTOCURRENCY WALLETS WITH REGARDS TO AML INVESTIGATION AND COMPLIANCE. <br/>
                CRYPTO DOWNGRADE RESERVES THE RIGHT TO TERMINATE OR REFUSE ACCOUNTS ON THE BASIS OF INFORMATION ATTAINED BY THE THIRD-PARTY COMPANIES THIS INCLUDES USERS CONNECTED TO “HIGH-RISK” WALLETS.
                CHIEF COMPLIANCE OFFICER <br/>
                THE CHIEF COMPLIANCE OFFICER IS THE PERSON, DULY AUTHORISED BY CRYPTO DOWNGRADE, WHOSE DUTY IS TO ENSURE THE EFFECTIVE IMPLEMENTATION AND ENFORCEMENT OF THE AML/CFT AND KYC POLICY. IT IS THE CHIEF COMPLIANCE OFFICER’S RESPONSIBILITY TO SUPERVISE ALL ASPECTS OF MyAltCoins ANTI-MONEY LAUNDERING AND COUNTER-TERRORIST FINANCING PROCEDURES, IN PARTICULAR:
                <br/>
                COLLECTION OF USERS’ IDENTIFICATION INFORMATION; <br/>
                ESTABLISHING AND UPDATING INTERNAL POLICIES AND PROCEDURES FOR THE COMPLETION, REVIEW, SUBMISSION AND RETENTION OF ALL REPORTS AND RECORDS REQUIRED UNDER THE APPLICABLE LAWS AND REGULATIONS; <br/>
                MONITORING TRANSACTIONS AND INVESTIGATING ANY SIGNIFICANT DEVIATIONS FROM NORMAL ACTIVITY; <br/> 
                IMPLEMENTING A RECORDS MANAGEMENT SYSTEM FOR APPROPRIATE STORAGE AND RETRIEVAL OF DOCUMENTS, FILES, FORMS AND LOGS, UPDATING RISK ASSESSMENT REGULARLY, PROVIDING LAW ENFORCEMENT WITH INFORMATION AS REQUIRED UNDER THE APPLICABLE LAWS AND REGULATIONS.<br/>
                THE CHIEF COMPLIANCE OFFICER IS THE CONTACT POINT FOR CRYPTO DOWNGRADE WITH LAW ENFORCEMENT AGENCIES FOR THE <br/>
                PURPOSES OF PREVENTION OF MONEY LAUNDERING, TERRORIST FINANCING AND OTHER ILLEGAL ACTIVITIES. <br/>
                TRANSACTION MONITORING <br/>
                CRYPTO DOWNGRADE USERS MUST COMPLETE THE MyAltCoins IDENTITY VERIFICATION PROCESS (WHO YOU ARE) BEFORE TRADING. AFTER <br/>
                VERIFICATION IS COMPLETED THE USER CONSENTS TO TRANSACTION MONITORING, CRYPTO DOWNGRADE ANALYSES USER’S TRANSACTIONAL PATTERNS (WHAT THEY DO). <br/>
                CRYPTO DOWNGRADE RELIES ON DATA ANALYSIS AS A RISK-ASSESSMENT AND SUSPICIOUS ACTIVITY DETECTION TOOLS. THESE TOOLS PERFORM A VARIETY OF COMPLIANCE-RELATED TASKS, INCLUDING CAPTURING DATA, FILTERING, RECORD-KEEPING, INVESTIGATION MANAGEMENT AND REPORTING. <br/>
                IN CONNECTION WITH THE AML/KYC POLICY, CRYPTO DOWNGRADE WILL: <br/>
                <br/>
                MONITOR ALL TRANSACTIONS. CRYPTO DOWNGRADE RESERVES THE RIGHT TO ENSURE THAT TRANSACTIONS OF SUSPICIOUS NATURE ARE REPORTED TO THE PROPER LAW ENFORCEMENT; <br/>
                REQUEST THE USER TO PROVIDE ANY ADDITIONAL INFORMATION AND DOCUMENTS IN CASE OF SUSPICIOUS TRANSACTIONS; <br/>
                SUSPEND OR TERMINATE USER’S ACCOUNT WHEN CRYPTO DOWNGRADE HAS A REASONABLE SUSPICION THAT SUCH USER IS ENGAGED IN ILLEGAL ACTIVITY. <br/>
                HOWEVER, THE ABOVE LIST IS NOT EXHAUSTIVE AND THE CHIEF COMPLIANCE OFFICER WILL MONITOR USERS’ TRANSACTIONS ON A REGULAR BASIS IN ORDER TO DEFINE WHETHER SUCH TRANSACTIONS ARE TO BE REPORTED AND TREATED AS SUSPICIOUS. RISK ASSESSMENT <br/>
                IN ORDER TO MEET ITS OBLIGATIONS REGARDING ANTI-MONEY LAUNDERING (AML) AND COUNTER TERRORIST FINANCING (CTF) CRYPTO DOWNGRADE COMPLETES AN ANNUAL AML RISK ASSESSMENT. THE AIM OF THE AML RISK ASSESSMENT IS TO PREVENT CRIMINALS USING CRYPTO DOWNGRADE TO LAUNDER MONEY BY HIGHLIGHTING RISKS AND ASSESSING CONTROLS CRYPTO DOWNGRADE HAS PUT IN PLACE. A RISK-BASED APPROACH IS TAKEN TO IDENTIFY USERS AND MONITOR HOW THEY USE OUR SERVICES. <br/>
                THE CHIEF COMPLIANCE OFFICER IS RESPONSIBLE FOR MANAGING FINANCIAL CRIME RISKS AND MAKING IMPROVEMENTS IN FINANCIAL CRIME RISK MANAGEMENT THROUGH IDENTIFYING THE GENERAL AND SPECIFIC MONEY LAUNDERING RISKS THAT CRYPTO DOWNGRADE IS FACING, DETERMINING HOW THESE RISKS ARE MITIGATED BY THE MyAltCoins AML CONTROLS AND ESTABLISHING THE RESIDUAL RISK THAT REMAINS FOR CRYPTO DOWNGRADE. COUNTRY OF RESIDENCE <br/>
                MyAltCoins AML AND KYC POLICY SETS OUT MyAltCoins RISK APPETITE WITH REGARD TO AML/KYC. TO REDUCE THIS RISK CRYPTO DOWNGRADE DOES NOT ACCEPT CLIENTS WHO ARE RESIDENT IN COUNTRIES DEEMED TO BE ABOVE THE MyAltCoins RISK APPETITE. <br/>
                THE SOURCES USED WITH REGARDS TO THE CATEGORISATION WERE:
                <br/>
                TRANSPARENCY INTERNATIONAL;<br/>
                KNOW YOUR COUNTRY;<br/>
                FATF HIGH RISK JURISDICTIONS;<br/>
                EU HIGH RISK JURISDICTIONS;<br/>
                COUNTRIES WHERE DIGITAL ASSETS ARE PROHIBITED OR THERE ARE RESTRICTIONS ON TRADING;<br/>
                COUNTRIES WHERE DIGITAL ASSETS ARE NOT PROHIBITED;<br/>
                COUNTRIES SUBJECT TO UNSC SANCTIONS REGIME.<br/>
                IT MUST ME CLEAR THAT MyAltCoins POLICY IS THAT ALL CLIENTS RESIDENT IN THE BELOW COUNTRIES ARE BANNED AND CANNOT BE ACCEPTED AS A CLIENT. ANY CLIENTS THAT TRY TO OPEN AN ACCOUNT WILL BE DENIED AND ANY<br/>
                FUNDS RETURNED TO SOURCE.<br/>
                FULL LIST OF BANNED JURISDICTIONS<br/>

                AFGHANISTAN<br/>
                ALBANIA<br/>
                ANGOLA<br/>
                ALGERIA<br/>
                BANGLADESH<br/>
                BARBADOS<br/>
                BOLIVIA<br/>
                BOTSWANA<br/>
                BURMA (MYANMAR)<br/>
                BURUNDI<br/>
                CAMBODIA<br/>
                CENTRAL AFRICAN REPUBLIC<br/>
                CHAD<br/>
                CONGO<br/>
                GUINEA – CONAKRY<br/>
                COTE D’IVOIRE<br/>
                CRIMEA (UKRAINE REGION)<br/>
                CUBA<br/>
                DEMOCRATIC PEOPLE’S REPUBLIC OF KOREA (DPRK)<br/>
                ECUADOR<br/>
                EGYPT<br/>
                EQUATORIAL GUINEA<br/>
                ERITREA<br/>
                GHANA<br/>
                GUINEA BISSAU<br/>
                GUYANA<br/>
                HAITI<br/>
                IRAN<br/>
                IRAQ<br/>
                JAMAICA<br/>
                LAO PDR<br/>
                LEBANON<br/>
                LIBYA<br/>
                MALI<br/>
                MOROCCO<br/>
                MYANMAR<br/>
                NEPAL<br/>
                NICARAGUA<br/>
                NORTH MACEDONIA<br/>
                PAKISTAN<br/>
                PANAMA<br/>
                QATAR<br/>
                SAUDI ARABIA<br/>
                SOMALIA<br/>
                SOUTH SUDAN<br/>
                SUDAN<br/>
                SYRIA<br/>
                TUNISIA<br/>
                UGANDA<br/>
                VANUATU<br/>
                VENEZUELA<br/>
                YEMEN<br/>
                ZIMBABWE<br/>
                CRYPTO DOWNGRADE ALSO DOES NOT ACCEPT ANY CLIENTS FROM DISPUTED TERRITORIES AS THEY DO NOT PRODUCE RECOGNISED OFFICIAL DOCUMENTS, THESE INCLUDE: <br/>

                DONETSK PEOPLE’S REPUBLIC (DPR)/LUHANSK PEOPLE’S REPUBLIC (LPR) <br/>
                PRIDNESTROVIAN MOLDAVIAN REPUBLIC <br/>
                NAGORNO-KARABAKH REPUBLIC <br/>
                REPUBLIC OF ABKHAZIA <br/>
                REPUBLIC OF SOMALILAND <br/>
                REPUBLIC OF SOUTH OSSETIA <br/>
                TURKISH REPUBLIC OF NORTHERN CYPRUS <br/>
                REPUBLIC OF CHINA (TAIWAN) <br/>
                PASSPORTS ISSUED BY THE RUSSIAN FEDERATION IN CRIMEA AND PASSPORTS ISSUED TO RESIDENTS OF DONETSK AND LUHANSK REGIONS OF UKRAINE DO NOT QUALIFY FOR VERIFICATION <br/>
                REPUBLIC OF KOSOVO <br/>
                SAHRAWI ARAB DEMOCRATIC REPUBLIC <br/>
                REPUBLIC OF ARTSAKH <br/>
                </div>
            </div>  
        </section>
    )
}

export default AmlKyc
